name: Mercari Monitor

permissions:
  contents: write

on:
  schedule:
    - cron: '*/10 * * * *'

  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
  with:
    persist-credentials: true
    
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Run script
        run: python main.py
      
      - name: Commit last_url
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add last_url.txt

          git commit -m "update last url" || echo "No changes"

          git push
